# Generated by Django 5.2.5 on 2025-08-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0005_customuser_address_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], default='', max_length=1, verbose_name='gender'),
        ),
    ]
