# Generated by Django 5.2.5 on 2025-08-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app', '0007_customuser_is_active_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_llm',
            field=models.CharField(choices=[('openai', 'OpenAI GPT'), ('gemini', 'Google Gemini')], default='openai', max_length=10),
        ),
    ]
